### ISSUE TITLE
may I know your pytorch vision?

### ISSUE THREAD

**Issue by wheat-yjy** [tbung/revnet#6]
it tell me "torch' has no attribute 'no_grad"

**Comment by tbung** [comment]
To use the master branch you will need pytorch 0.4.0, this is currently only available through building it yourself. You can try using the pytorch-0.3 branch in this repo.

**Comment by wheat-yjy** [comment]
thank you for reply! I am trying to reinstall pytorch.

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=http://mail-online.nosdn.127.net/sm385189165a0e3d30b9988917fa6ae78d.jpg&name=junyiyu07&uid=junyiyu07%40outlook.com&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ajunyiyu07%40outlook.com%22%5D>
[http://mail-online.nosdn.127.net/sm385189165a0e3d30b9988917fa6ae78d.jpg]
junyiyu07
邮箱：junyiyu07@outlook.com


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2018年04月27日 00:40，Till Bungert<mailto:notifications@github.com> 写道：

To use the master branch you will need pytorch 0.4.0, this is currently only available through building it yourself. You can try using the pytorch-0.3 branch in this repo.

**Comment by tbung** [comment]
Just thought you may want to know that pytorch 0.4 has been released one day befor I answered you, so you should not have to rebuild it yourself. If you find specific compatibility issues please report them and I will do my best to fix them.

**Comment by tbung** [comment]
Closed due to inactiveness.
